version: "3.9"

services:
  pokemon-api:
    container_name: pokemon-api
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
    profiles: ["dev"]

  pokemon-api-prod:
    container_name: pokemon-api-prod
    image: ton-dockerhub-username/pokemon-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    profiles: ["prod"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles: ["dev", "prod"]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: ["dev", "prod"]
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
